import { BackendUserProfile } from "../types";

export function generateFallbackRoadmap(profile: BackendUserProfile = {}) {
  const targetRole = profile.targetRole || "Full-Stack Generative AI Engineer";
  const name = profile.name || "Learner";
  const weeklyHours = profile.weeklyCommitmentHours || 10;

  return {
    id: `roadmap-${Date.now()}`,
    title: `${targetRole} Accelerator Roadmap`,
    summary: `A high-impact, milestone-driven pathway tailored for ${name} transitioning into ${targetRole} with an emphasis on practical systems, hands-on portfolio milestones, and modern tooling.`,
    targetRole,
    totalEstimatedWeeks: Math.ceil(80 / weeklyHours),
    totalEstimatedHours: 84,
    difficulty: profile.experienceLevel || "Intermediate",
    aiPersonalizationNotes: `Roadmap calibrated for ${weeklyHours}h/week with preference for ${profile.learningStyle || "hands-on projects"}. Prioritized skill bridge in foundational architecture, real-time agentic reasoning, and production deployments.`,
    createdAt: new Date().toISOString(),
    isFallback: true,
    fallbackReason: "Live AI Model Service is disconnected or API key is missing. Showing offline starter preview roadmap.",
    skillGaps: [
      {
        skill: "Generative AI & LLM Systems",
        category: "AI & Machine Learning",
        currentProficiency: 30,
        targetProficiency: 90,
        gapSeverity: "critical",
        importance: "Essential for modern AI engineering",
        recommendedFocus: "RAG architectures, vector embeddings, and tool calling",
      },
      {
        skill: "Vector Databases & Semantic Retrieval",
        category: "Data & Storage",
        currentProficiency: 25,
        targetProficiency: 85,
        gapSeverity: "critical",
        importance: "Core backbone of contextual AI systems",
        recommendedFocus: "Pinecone, pgvector, hybrid search & reranking",
      },
      {
        skill: "Distributed Microservices & APIs",
        category: "Backend & Systems",
        currentProficiency: 60,
        targetProficiency: 85,
        gapSeverity: "moderate",
        importance: "Scalable serving of inference workloads",
        recommendedFocus: "FastAPI, asynchronous streaming, WebSocket pipelines",
      },
      {
        skill: "Prompt Evaluation & Guardrails",
        category: "AI Quality & Security",
        currentProficiency: 20,
        targetProficiency: 80,
        gapSeverity: "critical",
        importance: "Production safety and deterministic testing",
        recommendedFocus: "LlamaIndex evals, Ragas, LangSmith test harnesses",
      },
      {
        skill: "Modern Frontend & Visualizations",
        category: "Frontend & UX",
        currentProficiency: 65,
        targetProficiency: 80,
        gapSeverity: "minor",
        importance: "Delivering responsive real-time user experiences",
        recommendedFocus: "React 19, Motion, SSE streaming and canvas charts",
      },
    ],
    phases: [
      {
        phaseIndex: 1,
        title: "Phase 1: Foundations & Semantic Architecture",
        description: "Establish strong foundations in LLM APIs, embedding spaces, and vector retrieval mechanics.",
        estimatedHours: 20,
      },
      {
        phaseIndex: 2,
        title: "Phase 2: RAG Pipelines & Knowledge Systems",
        description: "Build robust Retrieval-Augmented Generation architectures with multi-source hybrid search.",
        estimatedHours: 26,
      },
      {
        phaseIndex: 3,
        title: "Phase 3: Agentic Workflows & Multi-Modal Systems",
        description: "Implement autonomous tool-calling agents, memory management, and structured schema outputs.",
        estimatedHours: 24,
      },
      {
        phaseIndex: 4,
        title: "Phase 4: Production Evaluation & Capstone Deployment",
        description: "Deploy scalable inference backends, implement latency metrics, and build a capstone portfolio system.",
        estimatedHours: 14,
      },
    ],
    steps: [
      {
        id: "step-1",
        title: "LLM Fundamentals & Modern SDK Tooling",
        shortSummary: "Master prompt engineering, structured JSON generation, and client-server API contracts.",
        detailedDescription: "Learn how modern generative models parse system instructions, handle temperature parameters, and enforce strict type schemas via modern SDKs like @google/genai.",
        phaseIndex: 1,
        phaseName: "Phase 1: Foundations & Semantic Architecture",
        estimatedHours: 8,
        order: 1,
        prerequisites: [],
        skillsAcquired: ["Prompt Engineering", "Structured Schema Generation", "Gemini 3.7 API", "SDK Architecture"],
        deliverable: "An interactive command-line / API service that extracts unstructured text into validated TypeScript objects.",
        status: "in_progress",
        userNotes: "",
        reasoning: "Recommended because your baseline in LLM Systems is at 30% while target requires 90%. Establishing deterministic prompt schemas and SDK client wrappers is the mandatory prerequisite before building vector search and autonomous agents.",
        aiWhyRecommended: "Bridging the gap between raw text generation and predictable, schema-validated engineering output is the foundation for all subsequent agentic work.",
        aiTips: [
          "Always test edge cases in schema validation using malformed inputs.",
          "Use system instructions to anchor model persona and output constraints.",
        ],
        resources: [
          {
            id: "res-1",
            title: "Generative AI Engineering with Gemini & Modern SDKs",
            provider: "Google Cloud & DeepLearning.AI",
            type: "course",
            url: "https://www.deeplearning.ai",
            duration: "4 hours",
            cost: "Free",
            difficulty: "Beginner",
            rating: 4.9,
            skillsCovered: ["Prompt Design", "Function Calling", "Multimodal inputs"],
            aiRecommendationRationale: "Provides hands-on code examples matching your target role requirements exactly.",
          },
          {
            id: "res-2",
            title: "Prompt Engineering Guide & Structured Outputs",
            provider: "DAIR.AI Research",
            type: "article",
            url: "https://www.promptingguide.ai",
            duration: "2 hours",
            cost: "Free",
            difficulty: "Beginner",
            rating: 4.8,
            skillsCovered: ["Few-shot learning", "Chain of thought", "Schema constraints"],
            aiRecommendationRationale: "Industry standard reference for prompt optimization techniques.",
          },
        ],
        assessment: {
          title: "LLM SDK & Schema Mastery Quiz",
          questions: [
            {
              question: "Why is structured JSON output schema enforcement critical in software applications using LLMs?",
              options: [
                "It makes the LLM run faster on GPU hardware",
                "It guarantees deterministic parsing for frontend and backend databases",
                "It reduces token cost to zero",
                "It disables model reasoning completely",
              ],
              correctIndex: 1,
              explanation: "Structured schemas ensure the LLM returns predictable data types that your application code can safely parse without crashing.",
            },
            {
              question: "Which model parameter primarily controls the randomness or creativity of generation?",
              options: ["topK", "temperature", "maxOutputTokens", "seed"],
              correctIndex: 1,
              explanation: "Temperature scales the logits before softmax; lower values (e.g. 0.2) yield deterministic outputs, while higher values yield more creative diversity.",
            },
            {
              question: "Where should sensitive API keys be initialized in a production full-stack web application?",
              options: [
                "Inside browser localStorage",
                "Directly in React component props",
                "Exclusively in server-side environment variables",
                "In public GitHub repositories",
              ],
              correctIndex: 2,
              explanation: "API keys must always be secured on the server backend to prevent unauthorized extraction.",
            },
          ],
        },
      },
      {
        id: "step-2",
        title: "Vector Embeddings & Semantic Search Pipelines",
        shortSummary: "Convert textual and multimodal data into high-dimensional vector representations and search with cosine similarity.",
        detailedDescription: "Deep dive into embedding models, dimension reduction, distance metrics (Cosine vs Dot Product vs Euclidean), and vector indexing methods like HNSW.",
        phaseIndex: 1,
        phaseName: "Phase 1: Foundations & Semantic Architecture",
        estimatedHours: 12,
        order: 2,
        prerequisites: ["step-1"],
        skillsAcquired: ["Vector Embeddings", "Cosine Similarity", "pgvector / Pinecone", "Semantic Indexing"],
        deliverable: "A semantic search engine that indexes 100+ documents and retrieves the top-k relevant passages by intent.",
        status: "up_next",
        userNotes: "",
        reasoning: "Recommended because your Vector Databases skill gap is critical (25% vs 85% target). High-dimensional embeddings and cosine similarity indexing form the core retrieval backbone for production RAG.",
        aiWhyRecommended: "Your profile indicates intermediate backend knowledge, so mastering embedding spaces will unlock high-accuracy search capabilities.",
        aiTips: [
          "Remember that embeddings capture conceptual meaning rather than exact keyword matches.",
          "Normalize your vectors when using dot product for cosine similarity speedup.",
        ],
        resources: [
          {
            id: "res-3",
            title: "Vector Databases: from Embeddings to Production",
            provider: "Stanford Online",
            type: "course",
            url: "https://online.stanford.edu",
            duration: "6 hours",
            cost: "Free",
            difficulty: "Intermediate",
            rating: 4.9,
            skillsCovered: ["HNSW", "IVF", "Cosine Distance", "Vector Indexing"],
            aiRecommendationRationale: "Stanford's curriculum teaches the mathematical foundations alongside scalable engineering practice.",
          },
        ],
        assessment: {
          title: "Vector Search Foundations Check",
          questions: [
            {
              question: "What does a high cosine similarity (close to 1.0) between two vector embeddings indicate?",
              options: [
                "The documents have identical character lengths",
                "The texts share strong semantic and conceptual alignment",
                "The texts were written by the same author",
                "The vector database has run out of memory",
              ],
              correctIndex: 1,
              explanation: "Cosine similarity measures the angle between vectors; values near 1.0 indicate very close semantic direction.",
            },
            {
              question: "Why is HNSW (Hierarchical Navigable Small World) widely used in vector databases?",
              options: [
                "It enables approximate nearest neighbor (ANN) search with logarithmic time complexity",
                "It encrypts passwords inside the database",
                "It converts text into HTML automatically",
                "It is a relational SQL join syntax",
              ],
              correctIndex: 0,
              explanation: "HNSW allows fast approximate search across millions of vectors without performing an exhaustive linear scan.",
            },
          ],
        },
      },
      {
        id: "step-3",
        title: "Production RAG & Hybrid Retrieval Architectures",
        shortSummary: "Build resilient document chunking, metadata filtering, and re-ranking pipelines.",
        detailedDescription: "Combine dense vector search with sparse keyword search (BM25) and apply cross-encoder re-rankers to maximize context precision.",
        phaseIndex: 2,
        phaseName: "Phase 2: RAG Pipelines & Knowledge Systems",
        estimatedHours: 14,
        order: 3,
        prerequisites: ["step-2"],
        skillsAcquired: ["Hybrid Search (BM25 + Dense)", "Chunking Strategies", "Cross-Encoder Reranking", "Context Compression"],
        deliverable: "A fully functional Q&A assistant over technical PDF documents with citation highlights.",
        status: "locked",
        userNotes: "",
        reasoning: "Recommended because your learner profile specifies a hands-on project style and aims for enterprise knowledge systems. Hybrid retrieval solves production hallucination problems.",
        aiWhyRecommended: "Directly addresses your target role requirement for enterprise knowledge systems.",
        aiTips: [
          "Experiment with sliding window chunking with 15% overlap to avoid cutting sentences midway.",
        ],
        resources: [
          {
            id: "res-4",
            title: "Advanced Retrieval for AI Applications",
            provider: "DeepLearning.AI",
            type: "interactive",
            url: "https://www.deeplearning.ai",
            duration: "5 hours",
            cost: "Free",
            difficulty: "Intermediate",
            rating: 4.9,
            skillsCovered: ["Hybrid Search", "Reciprocal Rank Fusion", "Query Expansion"],
            aiRecommendationRationale: "Taught by leading industry practitioners with interactive Jupyter labs.",
          },
        ],
        assessment: {
          title: "RAG Architecture Assessment",
          questions: [
            {
              question: "What is the primary benefit of Hybrid Search over pure vector search?",
              options: [
                "It eliminates the need for an LLM completely",
                "It combines semantic conceptual matching with exact keyword/code precision (BM25)",
                "It reduces server memory consumption by 90%",
                "It prevents users from asking long questions",
              ],
              correctIndex: 1,
              explanation: "Hybrid search merges the strengths of semantic understanding with exact acronym and keyword identification.",
            },
          ],
        },
      },
      {
        id: "step-4",
        title: "Autonomous Tool-Calling Agents & Memory Systems",
        shortSummary: "Implement function declarations, recursive execution loops, and long-term conversation state.",
        detailedDescription: "Teach LLMs to call external APIs (database queries, weather, calculations, search), handle tool return payloads, and maintain conversational memory.",
        phaseIndex: 3,
        phaseName: "Phase 3: Agentic Workflows & Multi-Modal Systems",
        estimatedHours: 14,
        order: 4,
        prerequisites: ["step-3"],
        skillsAcquired: ["Tool Calling", "Function Calling Protocols", "ReAct Framework", "Multi-Agent Coordination"],
        deliverable: "An automated research agent that queries web APIs, analyzes tabular data, and generates executive briefing notes.",
        status: "locked",
        userNotes: "",
        reasoning: "Recommended because your target role is Full-Stack Generative AI Engineer where agentic function calling and multi-step tool loops are highest priority industry skills.",
        aiWhyRecommended: "Agentic tool calling is the single most in-demand capability for modern full-stack AI roles.",
        aiTips: [
          "Always implement a maximum iteration guard to prevent runaway execution loops.",
        ],
        resources: [
          {
            id: "res-5",
            title: "Building Multi-Agent Systems & Tools",
            provider: "Fast.ai & GitHub Labs",
            type: "project",
            url: "https://fast.ai",
            duration: "8 hours",
            cost: "Free",
            difficulty: "Advanced",
            rating: 4.9,
            skillsCovered: ["Autonomous Agents", "Tool Routing", "State Graphs"],
            aiRecommendationRationale: "Comprehensive project-based walk-through with real production patterns.",
          },
        ],
        assessment: {
          title: "Agentic Workflows Check",
          questions: [
            {
              question: "What is the role of the ReAct (Reasoning + Acting) loop in autonomous agents?",
              options: [
                "To compile JavaScript code into WebAssembly",
                "To alternate between generating a thought, taking an action (tool call), and observing the result",
                "To render React components on mobile phones",
                "To reboot the server if errors occur",
              ],
              correctIndex: 1,
              explanation: "ReAct combines reasoning traces with concrete actions and observations to solve complex multi-step problems.",
            },
          ],
        },
      },
      {
        id: "step-5",
        title: "Production Deployment, Observability & Capstone",
        shortSummary: "Deploy low-latency streaming endpoints with Docker, Cloud Run, token telemetry, and automated eval suites.",
        detailedDescription: "Containerize your AI application, configure server-sent events (SSE) for fluid streaming, log token latency metrics, and test accuracy with automated benchmarks.",
        phaseIndex: 4,
        phaseName: "Phase 4: Production Evaluation & Capstone Deployment",
        estimatedHours: 16,
        order: 5,
        prerequisites: ["step-4"],
        skillsAcquired: ["Docker & Cloud Run", "SSE Streaming", "LLM Observability", "Ragas / LLM Evals", "CI/CD"],
        deliverable: "A live, deployed multi-tenant AI system with public URL, telemetry dashboard, and GitHub repository.",
        status: "locked",
        userNotes: "",
        reasoning: "Recommended because your backend and cloud deployment skills need synthesis into a verifiable portfolio deliverable for hiring evaluation.",
        aiWhyRecommended: "Completing this capstone gives you a tangible portfolio project to showcase in tech job interviews.",
        aiTips: [
          "Include an architectural diagram and live demo link prominently in your GitHub README.",
        ],
        resources: [
          {
            id: "res-6",
            title: "Full-Stack AI Production Engineering",
            provider: "MIT OpenCourseWare",
            type: "course",
            url: "https://ocw.mit.edu",
            duration: "10 hours",
            cost: "Free",
            difficulty: "Advanced",
            rating: 5.0,
            skillsCovered: ["Docker", "Kubernetes", "Observability", "Prometheus"],
            aiRecommendationRationale: "Covers battle-tested infrastructure patterns used by top tech companies.",
          },
        ],
        assessment: {
          title: "Production Readiness Capstone Check",
          questions: [
            {
              question: "Why is Server-Sent Events (SSE) preferred over standard request-response for chat interfaces?",
              options: [
                "It provides perceived instant response time by streaming tokens as they are generated",
                "It compresses images by 99%",
                "It bypasses all cloud security firewalls",
                "It removes the need for a web browser",
              ],
              correctIndex: 0,
              explanation: "Streaming tokens via SSE dramatically improves user experience by eliminating the 5-10s waiting barrier.",
            },
          ],
        },
      },
    ],
  };
}
